
networks:
  laravel:
    driver: bridge

services:
  #server
  nginx_laravel:
    image: nginx:alpine
    container_name: nginx_laravel
    restart: unless-stopped
    build:
        context: ./nginx
    tty: true
    ports:
      - "8081:81"
    volumes:
      - ./:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  #database
  mysql:
      image: mariadb:10.4.8
      restart: unless-stopped
      container_name: mysql
      tty: true
      ports:
        - "3307:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-laravel}
        MYSQL_USER: ${DB_USERNAME:-root}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
        SERVICE_NAME: mysql
      volumes:
        - ./mysql/data:/var/lib/mysql
      networks:
        - laravel
  #laravel
  php:
    container_name: ganadex_backend
    build:
      context: .
      dockerfile: DockerFile
    environment:
      DB_HOST: mysql  #los host frecuentemente son las mismo el nombre del servicio
      DB_PASSWORD: root
      APP_URL: http://nginx_laravel
      SESSION_DOMAIN: ganadex_frontend
      SANCTUM_STATEFUL_DOMAINS: ganadex_frontend
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/app
    networks:
      - laravel
    depends_on:
      - mysql

